
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServcieImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8989/WS_Server/Webservice?wsdl")
public class WebServcieImplService
    extends Service
{

    private final static URL WEBSERVCIEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVCIEIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVCIEIMPLSERVICE_QNAME = new QName("http://service/", "WebServcieImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8989/WS_Server/Webservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVCIEIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVCIEIMPLSERVICE_EXCEPTION = e;
    }

    public WebServcieImplService() {
        super(__getWsdlLocation(), WEBSERVCIEIMPLSERVICE_QNAME);
    }

    public WebServcieImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVCIEIMPLSERVICE_QNAME, features);
    }

    public WebServcieImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVCIEIMPLSERVICE_QNAME);
    }

    public WebServcieImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVCIEIMPLSERVICE_QNAME, features);
    }

    public WebServcieImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServcieImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServcieImpl
     */
    @WebEndpoint(name = "WebServcieImplPort")
    public WebServcieImpl getWebServcieImplPort() {
        return super.getPort(new QName("http://service/", "WebServcieImplPort"), WebServcieImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServcieImpl
     */
    @WebEndpoint(name = "WebServcieImplPort")
    public WebServcieImpl getWebServcieImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "WebServcieImplPort"), WebServcieImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVCIEIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVCIEIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVCIEIMPLSERVICE_WSDL_LOCATION;
    }

}
